services:
  identity-service:
    build: ./
    container_name: identity-service
    depends_on:
      - identity-db
    environment:
      DATABASE_URL: postgres+psycopg2://identity_user:identity_pass@identity-db:5432/identity_db
      JWT_SECRET_KEY: "supersecret"
      JWT_ALGORITHM: "HS256"
      JWT_ACCESS_TOKEN_EXPIRE_MINUTES: 30
    ports:
      - "8002:8000"

  identity-db:
    image: postgres:15
    container_name: identity-db
    environment:
      POSTGRES_USER: identity_user
      POSTGRES_PASSWORD: identity_pass
      POSTGRES_DB: identity_db
    volumes:
      - identity_db_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

volumes:
  identity_db_data:
